### ISSUE TITLE
How should the downloadable standard be hosted in github?

### ISSUE THREAD

**Issue by mdoering** [tdwg/tapir#1]
The original TAPIR standard can be downloaded as a zip archive like other TDWG standards from http://www.tdwg.org/standards/449/

That archive only contains the v1.0 xml schema files plus the specification as html & css files.
The original TAPIR svn repository does contain a lot more files (cns, cs, etc), source files to generate the html specification and logo files. 

I would prefer to keep these svn files in the master branch of the git repository. The tagged 1.0 version of the repo then contains many more files than the original zip. Does that matter as long as the files in the zip are the exact same ones as in the master branch? Or do we want to maintain another normative branch that only contains the final core files?

**Comment by mdoering** [comment]
@peterdesmet has the infrastructure group decided about this already?

**Comment by peterdesmet** [comment]
Hi @tdwg/infrastructure group, can you weigh in on this issue? To me, what @mdoering proposes is fine:
1. Host all svn files on GitHub
2. Consider the tagged 1.0 version of the files as the download of version 1.0 (we do the same for Darwin Core), even though it contains more files than the download currently served from http://www.tdwg.org/standards/449/, as long as the respective files are the same.

**Comment by mdoering** [comment]
@tdwg/infrastructure I take no objection as an ok. Noone thinks we need to preserve the actual exact file archive, maybe even bytes, right?

**Comment by CynthiaParr-USDA** [comment]
I certainly have no objection, have you consulted the TAPIR task group convener, Renato De Giovanni renato@cria.org.br?

I really can't see why it would be a problem, though.

**Comment by mdoering** [comment]
I have consulted Renato and as noone objected so far I am closing this issue

**Comment by regiov** [comment]
Hi, sorry, I was travelling these days and only now I'm able to respond. I didn't even remember about that zip file. All we need, in my opinion, is to keep the links to the most important resources. I don't mind including other files to the 1.0 tag.
