### ISSUE TITLE
Feature request: search a database and get the list of matching identifiers

### ISSUE THREAD

**Issue by etorres** [tdwg/tapir#6]
It would be easier to maintain a local collection updated if an operation (or output model) is provided to search a database and get the list of matching identifiers. This would help to reduce the amount of data transferred by avoiding that complete datasets are downloaded using a data model like Darwin Core just to check whether the record is available in the local database.

For example, the NCBI's Entrez programming utilities provide this feature with ESearch, a search facility that responds to a text query with the list of matching identifiers in a given database (for later use in other database operations).

Thanks in advance!

**Comment by regiov** [comment]
Hi Erik, if I understood correctly, you could use the inventory operation to get a list of unique identifiers currently available on the server side and then compare them with the identifiers in your local database. Inventory operations also accept filters if necessary, so if the service has fields such as date of inclusion and/or modification you could include them in your filters.
Hope this helps...
